# Generated by Django 6.0.2 on 2026-04-05 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAMEDEX', '0005_comunidad_publicacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='comunidad',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='comunidades/'),
        ),
    ]
