# Generated by Django 6.0.2 on 2026-03-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GAMEDEX', '0002_producto_creado_producto_publicado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='cantidad',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='producto',
            name='dias_garantia',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
